### ISSUE TITLE
Right space next to string in Arabic is not consistent for right-aligned strings

### ISSUE THREAD

**Issue by kreier** [kreier/timeline#51]
The timeline has strings both right and left aligned. With using the font shape engine and `fpdf2` this usually works fine, but some strings have a little extra space to it. After some testing I found the problem: When latin strings (or even numbers) are rendered, the font shape engine switches to latin. In the next round of determining the string width, the latin setting is used to measure the width, and after that the language is changed. In a sequence where a latin character is drawn to the pdf prior to the determination of the string width for a right aligned string the return value is not correct.

The problem was reported at fpdf2: https://github.com/py-pdf/fpdf2/issues/1231

**Comment by timeline24** [comment]
Isn't that fixed with a later edition of fpdf2?

**Comment by kreier** [comment]
Yes, fixed on July 27th by andersonhc at fpdf2.
